version: '3.8'

services:
  db:
    image: postgres:15
    container_name: postgres-db
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=enginedb
    volumes:
      - ./db_scripts:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432" # Exposing PostgreSQL port

  # pgAdmin service
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=admin_password
    ports:
      - "80:80" # Exposing pgAdmin on port 80 (http://localhost)
    depends_on:
      - db
    volumes:
      - pgadmin_data:/var/lib/pgadmin

# Volumes for persistence
volumes:
  pgadmin_data:
    driver: local
