version: '3.8'

services:
  ibmm24_engine:
    image: matfel/ibmm24-engine
    container_name: ibmm24-engine
    ports:
      - "8080:8080"  # Adjust the port mapping if needed
    environment:
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_NAME=${POSTGRES_DB}
      - DB_USER=${POSTGRES_USER}
      - DB_PASSWORD=${POSTGRES_PASSWORD}
    depends_on:
      - postgresql
    networks:
      - app_network

  postgresql:
    image: postgres:latest
    container_name: postgresql
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - ./db_scripts:/docker-entrypoint-initdb.d/generate_db.sql  # Mount the script
    ports:
      - "5432:5432"
    networks:
      - app_network

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: always
    ports:
      - "5050:80" # Expose pgAdmin on port 5050
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@pgadmin.local # Default login email
      PGADMIN_DEFAULT_PASSWORD: admin           # Default login password
    depends_on:
      - postgresql
    networks:
      - app_network

volumes:
  pg_data:
    driver: local

networks:
  app_network:
    driver: bridge
